<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.12" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WeddingBooking.Domain\WeddingBooking.Domain.csproj" />
    <ProjectReference Include="..\WeddingBooking.Infrastructure\WeddingBooking.Infrastructure.csproj" />
    <ProjectReference Include="..\WeddingBooking.Integrations\WeddingBooking.Integrations.csproj" />
  </ItemGroup>

</Project>
