// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WeddingBooking.Infrastructure.Persistence;

#nullable disable

namespace WeddingBooking.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(WeddingBookingDbContext))]
    [Migration("20260915184330_OpretBookinger")]
    partial class OpretBookinger
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WeddingBooking.Domain.Bookinger.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("Bryllupsdato")
                        .HasColumnType("date")
                        .HasColumnName("bryllupsdato");

                    b.Property<int?>("Gæsteantal")
                        .HasColumnType("integer")
                        .HasColumnName("gaesteantal");

                    b.Property<string>("Kundenavn")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("kundenavn");

                    b.Property<DateTimeOffset>("Oprettet")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("oprettet");

                    b.HasKey("Id");

                    b.HasIndex("Bryllupsdato");

                    b.ToTable("bookinger", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
